from os import environ


ULTRALOADER_CREDENTIAL_DIRECTORY = environ.get(
    "ULTRALOADER_CREDENTIAL_DIRECTORY", "~/.ultraloader"
)
ULTRALOADER_CREDENTIAL_FILE_PATH = environ.get(
    "ULTRALOADER_CREDENTIAL_FILE_PATH", f"{ULTRALOADER_CREDENTIAL_DIRECTORY}/creds.json"
)
